spring:
  profiles:
    active: sample-data,dev,secure

admin:
  user:
    password: 'admin'
    username: 'admin@devplant.ro'


app:
  security:
      private-key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAyUqydNMFWLf8Dhmu1WiPudElyLdZ7E0oGSmOGHcZMDFowVqN
        kAjzutm05f8NUZ8hU7TwYPu1bxq+/OKdbpdjPVgIhodjjmlj4fEO4FLrwyL3hjqs
        vGLVdoHQAzaO8TSbXPVRIyPhBKAkPBYIQZLbO2oeneUjJOSeu4k96NbjZL1cN81Y
        B9wCZblIBZrwoV+ZrVzc+XB0d7AQ6J3FkhRqyzvTuWVyFLKRGQynKI/dOpD/4681
        +Lcb73h4Lx5Sy5I5sFCXsDyxtE06zAuf+ZjuUtCQuJ6qyaUmkRE3L9rM7dZgDKzL
        eajv9laaD233vABKL8Y+XQpRoLxU6bA22pwk/QIDAQABAoIBAQDBwrqHg/14ihoB
        xK0r1ivLlUzGqd/Qe/DmT77tQ++mGVmaDb2I8WUT7q6YWmwKrqAZAGoHISRj354K
        tWUP6H/ps8z5Gmg11LMF8dH9EzTIsOcNeXt/F7AdFBYUkbcE7jvDPo0sw0O9/R0E
        Db1CycdoqNzx5nhu8fbt1M0YTYm0FHG7tbQV9sQKrztuAfHzE5+qHzXpy/gPPN7S
        fAONkRJMAQ6Tg08ss6U3oiTUi3di7jU6Z9S3frUR6JTjNJ7GjnhdUXIL4ZL1M6Ir
        lkQYzhVL3rHn7K3BeCXp/vRxYkb61ogY7Y+cUFgsg9nQGo/bKaZLbSDt4FkJcq/h
        IN1+Kr3tAoGBAOzvbTOI1wHEP5twsymtmHUbGoU0VKOK7CW7MAzNcb9o1MjBK+az
        b7CdSs6bWaGUGDIrgAvNzeXAxPp4j0P8RgAXc5OlKiJjL9+CScjs6s/AnBSYl1+m
        3Un8tFF54PxI+ZNiMgi91pE16qUm+RYFyL+eQtPXzlY41cKf5/vQnbtHAoGBANl9
        DxvdueSBwsIxlXoITyPmEu3IWwUzC+ALfO5ZCePGN1OKd9L4rszYdg1svhE55bEU
        XaxTwuXKZYA4ymspUNTGy/uZ65hsiESBaT8nUwlsy1Br++yaj8QgFswenv22PKJF
        HJWHIv8zwB1TeRsy4qM5gFjHXd7zriCNBT2J5LebAoGAZnByJ1jflNzzn1IPtFJg
        2yjXw4XHnlnfFcUj1jUxG8/IR+/0+i7UeGjZQhC6pPhxqadTGkdl4RMCV0SutHcr
        ELkS+F/toqZ9uUYMfrmoICCnmuQKdomfnXCLybpHQuyOM2G+PjdNwMSt6a+6/AGO
        NQLI4+ynQnIaQaZ/V0lwGNsCgYAX3SAGR7r49r/+/N/Q5w5/+uPC0YQjOumnqLsJ
        kB2Er6Ase3oQXRcZBPtXF8J3M2oflwN8QCiXfDDM8+5J+duTrUh+j/II5IfDNIvu
        0QrMcvKQHXkkCgWSWI8H0KhTYGagy4KKaayOYghHb3xPXrL9g/awRxfmucg2bCLS
        EMpW1wKBgCz6U0USmrMZcpXarf7eGD8lhjAb8jJv3DWoU0tRJAdNvI1tHIya/fvu
        5+haIzCVlCS6K5+qVlf/OilmLtUepG3VJyc5Qm/LHZL/WatXpdeoSdYW8nMbVrdU
        KuJaV5w8HwKhZSOPV7rcQPDZgXNYOe4xOkQQz/48PbeNXDIHyc6b
        -----END RSA PRIVATE KEY-----

      public-key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJSrJ00wVYt/wOGa7VaI+50SXIt1nsTSgZKY4YdxkwMWjBWo2QCPO62bTl/w1RnyFTtPBg+7VvGr784p1ul2M9WAiGh2OOaWPh8Q7gUuvDIveGOqy8YtV2gdADNo7xNJtc9VEjI+EEoCQ8FghBkts7ah6d5SMk5J67iT3o1uNkvVw3zVgH3AJluUgFmvChX5mtXNz5cHR3sBDoncWSFGrLO9O5ZXIUspEZDKcoj906kP/jrzX4txvveHgvHlLLkjmwUJewPLG0TTrMC5/5mO5S0JC4nqrJpSaRETcv2szt1mAMrMt5qO/2VpoPbfe8AEovxj5dClGgvFTpsDbanCT9 timobejan@Timos-MacBook-Pro.local
server:
  port: 9000
